firstname = input("Enter your first name")
lastname = input("Enter your last name")
age = input("Enter your age")
print(f"Hello, {lastname} {firstname} ! your age is {age}")
print(type(lastname))
print(type(age))
print(int(age) + 2)